decoupled ShowWeather from API key (it sucks having to retype that when enabling/disabling). Reduce VS warnings. Fixed weather option changes not taking effect immediately.
3rob3/ImmichFrame pull request #55
Opened 2024-04-16 00:29 UTC by 3rob3

2024-04-16 00:31 UTC, 3rob3 commented
decoupled ShowWeather from API key (it sucks having to retype that when enabling/disabling). Reduce VS warnings. Fixed weather option changes not taking effect immediately.

2024-04-16 07:00 UTC, JW-CH requested changes
My thoughts on your PR :)

2024-04-16 11:06 UTC, 3rob3 commented on ImmichFrame/Models/Settings.cs
> +    public bool ShowWeather { get; set; } = true;
Don't agree at all, but not enough to argue about it.

2024-04-16 11:10 UTC, 3rob3 commented on ImmichFrame/Helpers/WeatherHelper.cs
> +        public static async Task<WeatherInfo?> GetWeather(double latitude, double longitude, OpenWeatherMapOptions Options)
I guess, does it really matter though? That's what GC is for.

2024-04-16 11:15 UTC, 3rob3 commented on ImmichFrame/Views/MainView.axaml.cs
> +        _viewModel = new MainViewModel();
Don't really care, I was just trying to reduce warnings. We can leave it as it was before.

2024-04-16 11:19 UTC, JW-CH commented on ImmichFrame/Helpers/WeatherHelper.cs
> +        public static async Task<WeatherInfo?> GetWeather(double latitude, double longitude, OpenWeatherMapOptions Options)
I mean yea, but you have to spend resources to create a new instance of the weatheroptions every time you call that method.

2024-04-16 11:20 UTC, JW-CH commented on ImmichFrame/Models/Settings.cs
> +    public bool ShowWeather { get; set; } = true;
It just feels odd to have a setting for ShowWeather that will not work when no WeatherApiKey was set.

2024-04-16 22:43 UTC, 3rob3 commented on ImmichFrame/Helpers/WeatherHelper.cs
> +            OpenWeatherMapOptions options = new OpenWeatherMapOptions
I removed all the ShowWeather stuff, this I am leaving and we can fix in the future if it really bothers you. Because they are static everything I tried requires a new object to be created first. You can put it in the constructor, but then it behaves like before and is not updated when changes are made in settings.

2024-04-17 07:12 UTC, JW-CH approved these changes

2024-04-17 07:12 UTC, merged