Closes #58, Closes #61
3rob3/ImmichFrame pull request #62
Opened 2024-04-25 19:50 UTC by 3rob3

2024-04-25 19:52 UTC, 3rob3 commented
Closes #58, Closes #61

2024-04-26 02:12 UTC, abe-101 approved these changes
Thanks!

2024-04-26 08:52 UTC, JW-CH requested changes

2024-04-26 08:52 UTC, JW-CH commented on ImmichFrame/ViewModels/MainViewModel.cs
> +    public Task PauseImage()
Why does this method return a task?

2024-04-26 08:52 UTC, JW-CH commented on ImmichFrame/Views/SettingsView.axaml
> +              Content="Cancel"
Fix formatting? :)

2024-04-26 08:52 UTC, JW-CH commented on ImmichFrame/Views/SettingsView.axaml
> +              Content="Save"
Also Formatting

2024-04-26 11:55 UTC, 3rob3 commented on ImmichFrame/ViewModels/MainViewModel.cs
> +    public Task PauseImage()
Because it doesn't contain any awaits the method can't be async. This allows it to be awaited. How would you do it?

2024-04-26 11:57 UTC, 3rob3 commented on ImmichFrame/Views/SettingsView.axaml
> +              Content="Cancel"
Are you looking at it in VS? Looks correct to me.

2024-04-26 11:57 UTC, 3rob3 commented on ImmichFrame/Views/SettingsView.axaml
> +              Content="Save"
same

2024-04-26 12:17 UTC, JW-CH commented on ImmichFrame/ViewModels/MainViewModel.cs
> +    public Task PauseImage()
Why does it need to be awaited? Just return void and remove the await in the call.

2024-04-26 12:19 UTC, JW-CH commented on ImmichFrame/Views/SettingsView.axaml
> +              Content="Cancel"
Nope, was looking at it online.
![image](https://github.com/3rob3/ImmichFrame/assets/17313367/e785f3ef-64df-4205-a1d2-5552e9bd52ac)

2024-04-26 12:26 UTC, 3rob3 commented on ImmichFrame/Views/SettingsView.axaml
> +              Content="Cancel"
edited my comment, think its fixed now.

2024-04-26 13:02 UTC, merged