Margin setting
3rob3/ImmichFrame pull request #75
Opened 2024-05-13 13:16 UTC by 3rob3

Added Margin setting
Added NumericUpDown margins to align with other controls (unclear why this needs explicitly set, stackpanel should have done this)
Closes #74

2024-05-13 14:21 UTC, JW-CH requested changes

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/Settings.example.xml
> -	<ImmichServerUrl>http://YourIpOrUrl:2283</ImmichServerUrl>
Once again, the settings format was messed up.

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/Views/MainView.axaml
> +  <Grid ColumnDefinitions="*, *, *" RowDefinitions="*, *, *" Margin="{Binding Settings.Margin}">
Don't add this to all the views, we have the `WindowView` that could be that one place to set this. (The wrapper view). With that, all the views will have the needed `margin`.

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/Views/SettingsView.axaml
> +          <NumericUpDown Value="{Binding Settings.Interval}" FormatString="F0" Margin="10,0" />
Can you do the margin here as a style? Not really related tho this PR.

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/ViewModels/SettingsViewModel.cs
> +        private string margin;
Why adding a separate property? Just use `Settings.Margin`

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/Views/SettingsView.axaml
> +          <TextBox Text="{Binding Margin}" />
Use `Settings.Margin`.

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/Views/SettingsView.axaml
> +          <NumericUpDown Value="{Binding Settings.Interval}" FormatString="F0" Margin="10,0" />
Also Add the `FormatString` to the style

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/ViewModels/SettingsViewModel.cs
> +            Margin = new string(Settings.Margin.ToString());
The `.ToString()` already creates a string. I'd never create a new string with `new string()`. Also, this should not be needed since you can access `Settings.Margin`.

2024-05-13 14:21 UTC, JW-CH commented on ImmichFrame/ViewModels/SettingsViewModel.cs
> +                Settings.Margin = Thickness.Parse(Margin);
Use `Settings.Margin`.

2024-05-13 14:24 UTC, JW-CH commented
Ah and btw: The `Margin` on the `NumericUpDown` is needed, because the `Textblock` has a style.

2024-05-13 14:38 UTC, 3rob3 commented on ImmichFrame/Settings.example.xml
> -	<ImmichServerUrl>http://YourIpOrUrl:2283</ImmichServerUrl>
Must be a region thing, it is not messed up:
![image](https://github.com/3rob3/ImmichFrame/assets/156599986/4dcb73ac-a8b2-4526-a2e0-5df1ef87200f)

2024-05-13 14:40 UTC, 3rob3 commented on ImmichFrame/Views/SettingsView.axaml
> +          <NumericUpDown Value="{Binding Settings.Interval}" FormatString="F0" Margin="10,0" />
Agreed, good idea.

2024-05-13 14:40 UTC, JW-CH commented on ImmichFrame/Settings.example.xml
> -	<ImmichServerUrl>http://YourIpOrUrl:2283</ImmichServerUrl>
Your formatting adds two spaces, mine adds a tabstop

2024-05-13 14:47 UTC, JW-CH commented on ImmichFrame/Settings.example.xml
> -	<ImmichServerUrl>http://YourIpOrUrl:2283</ImmichServerUrl>
![image](https://github.com/3rob3/ImmichFrame/assets/17313367/bb8089b0-48ae-47bc-992c-e3cce60c0274)
what are your c# settings here? :)

2024-05-13 14:56 UTC, 3rob3 commented on ImmichFrame/ViewModels/SettingsViewModel.cs
> +                Settings.Margin = Thickness.Parse(Margin);
Settings.Margin is a Thickness, Margin is a string.

2024-05-13 14:58 UTC, 3rob3 commented on ImmichFrame/ViewModels/SettingsViewModel.cs
> +            Margin = new string(Settings.Margin.ToString());
Forgot to remove that, was troubleshooting

2024-05-13 15:09 UTC, 3rob3 commented on ImmichFrame/ViewModels/SettingsViewModel.cs
> +        private string margin;
Settings.Margin is a Thickness. You can't bind a TextBox text to a Thickness without a converter, this was far less code.

2024-05-13 15:10 UTC, 3rob3 commented on ImmichFrame/Views/SettingsView.axaml
> +          <TextBox Text="{Binding Margin}" />
Settings.Margin is a Thickness.

2024-05-13 15:12 UTC, 3rob3 commented on ImmichFrame/Settings.example.xml
> -	<ImmichServerUrl>http://YourIpOrUrl:2283</ImmichServerUrl>
Whatever the defaults are, in this case same as your screenshot.

2024-05-13 15:14 UTC, 3rob3 commented
> Ah and btw: The `Margin` on the `NumericUpDown` is needed, because the `Textblock` has a style.

Yeah, dumb mistake. Fixed.

2024-05-13 15:34 UTC, 3rob3 commented on ImmichFrame/Views/MainView.axaml
> +  <Grid ColumnDefinitions="*, *, *" RowDefinitions="*, *, *" Margin="{Binding Settings.Margin}">
Good catch, didn't think about that. Problem is I'm not sure how to do it :). It doesn't work setting it in the UserControl tag. It works if you set a Style for Grid, but SettingsView parent container is a DockPanel, not a grid.
How were you thinking?

2024-05-14 06:32 UTC, JW-CH commented on ImmichFrame/Views/MainView.axaml
> +  <Grid ColumnDefinitions="*, *, *" RowDefinitions="*, *, *" Margin="{Binding Settings.Margin}">
![image](https://github.com/3rob3/ImmichFrame/assets/17313367/d19ba94b-06fb-41d2-842f-e1e0a089f86a)
This works for me

2024-05-14 07:32 UTC, JW-CH commented on ImmichFrame/Views/MainView.axaml
> +  <Grid ColumnDefinitions="*, *, *" RowDefinitions="*, *, *" Margin="{Binding Settings.Margin}">
Maybe we also could set the background to black?

2024-05-14 10:57 UTC, 3rob3 commented on ImmichFrame/Views/MainView.axaml
> +  <Grid ColumnDefinitions="*, *, *" RowDefinitions="*, *, *" Margin="{Binding Settings.Margin}">
Yeah, that works for me too, but not when you set the binding. It just does nothing.

2024-05-14 11:01 UTC, 3rob3 commented on ImmichFrame/Views/MainView.axaml
> +  <Grid ColumnDefinitions="*, *, *" RowDefinitions="*, *, *" Margin="{Binding Settings.Margin}">
Try my branch with that change if you can, dev.3rob3.MarginControl

2024-05-14 11:40 UTC, JW-CH commented
I made a change to your PR, can you review that too?

2024-05-14 22:44 UTC, 3rob3 commented
> I made a change to your PR, can you review that too?

It works, but only updates Margin once (in the MainWindowViewModel constructor). So now you have to quit and re-open to get the new margin to apply.

2024-05-15 06:43 UTC, JW-CH commented
> > I made a change to your PR, can you review that too?
> 
> It works, but only updates Margin once (in the MainWindowViewModel constructor). So now you have to quit and re-open to get the new margin to apply. It also doesn't catch errors for invalid Margin values entered, it will just crash out and make you enter all your settings again. Moving the Margin stuff from the constructor to the Navigate method solves the first issue.
> 
> Also, I added the language to date/time change (its just a few lines in MainViewModel). This is for the issue bo0tzz submitted.

I created a new branch for the proper error page thing. I noticed that too. Other stuff will break too if you provide invalid settings.

2024-05-15 11:20 UTC, 3rob3 commented
So should I merge this then? What did you think about moving Margin= into Navigate?

2024-05-15 12:20 UTC, merged