Create an album for recent ImmichFrame displayed photos
3rob3/ImmichFrame pull request #82
Opened 2024-05-27 20:27 UTC by 3rob3

Closes #80

2024-05-28 07:45 UTC, JW-CH requested changes

2024-05-28 07:45 UTC, JW-CH commented on ImmichFrame/App.config
> +            <setting name="UseImmichFrameAlbum" serializeAs="String">
As with the API-Key settings some time ago. Wouldn't one name setting be enough? Like if you set a name, that implies that you want to use the ImmichFrame Album?

2024-05-28 07:45 UTC, JW-CH commented on ImmichFrame/Helpers/AssetHelper.cs
> +                var immichAlbums = await immichApi.GetAllAlbumsAsync(null, null);
Loading all albums when adding a photo seems odd to me. Could you store the album ID somehow, or at least cache it? (Cache it for all the requests)

2024-05-28 07:45 UTC, JW-CH commented on ImmichFrame/Views/MainView.axaml.cs
> +            await _assetHelper.DeleteImmichFrameAlbum();
It might be better to delete the "old" album on startup. If you close the app, you might still want to be able to see the last images in that album. Also, if the app crashes, the album will not be deleted.

A nice feature would be to have the last X images in there, if the app for example runs for a few days, you get huge albums without this feature. Not sure if this is possible.

2024-05-28 12:48 UTC, 3rob3 commented on ImmichFrame/App.config
> +            <setting name="UseImmichFrameAlbum" serializeAs="String">
Agreed, I will make this change. 
FYI:
Original implementation was just a checkbox, and album name was auto-created (ImmichFrame{machine name)) but I couldn't get it working on Android.

2024-05-28 12:57 UTC, 3rob3 commented on ImmichFrame/Views/MainView.axaml.cs
> +            await _assetHelper.DeleteImmichFrameAlbum();
This is on startup, not sure what you mean here.

For the second point, if I understand you correctly I do this already. I am only storing a maximum of 50 assets in the album, once you hit that I remove the oldest from the album, then add new one.

2024-05-30 14:55 UTC, JW-CH commented
I did not manage to test these changes right now. Will do when I get time. I am unsure about the album loading in the AssetHelper

2024-05-30 17:15 UTC, 3rob3 commented on ImmichFrame/Models/Settings.cs
> -                    if (!bool.TryParse(value.ToString(), out var boolValue))
OMG....oops.

2024-05-30 17:38 UTC, 3rob3 commented on ImmichFrame/Helpers/AssetHelper.cs
> +                var immichFrameAlbum = immichAlbums.FirstOrDefault(album => album.AlbumName == settings.ImmichFrameAlbumName);
Only deletes Album if there is one with same name as specified in ImmichFrameAlbumName. This is needed so we don't orphan images in that album. Only other option is to GetAllAbums, GetAllAssets in the album, remove asset for the album ( one at a time). End result is the same, just a lot more resources spent doing it.

2024-05-30 17:40 UTC, 3rob3 commented
> I did not manage to test these changes right now. Will do when I get time. I am unsure about the album loading in the AssetHelper

I have been thinking about how to improve this. I feel like it is more risk to remove it. Weird stuff could happen if someone deletes the album manually. It works well with negligible performance hit.

2024-05-31 12:23 UTC, JW-CH commented on ImmichFrame/Models/Settings.cs
> +                case "ImmichFrameAlbumName":
Can you consolidate this with Language and Clockformat? If the cases do the same, have them together.

2024-05-31 13:23 UTC, 3rob3 commented on ImmichFrame/Models/Settings.cs
> +                case "ImmichFrameAlbumName":
done. I did that on purpose so in the future we could validate language.

2024-05-31 16:56 UTC, JW-CH commented on ImmichFrame/App.axaml
> +             RequestedThemeVariant="Dark"
Good catch, did not know this was an option.

2024-06-02 20:47 UTC, 3rob3 commented on ImmichFrame/Helpers/AssetHelper.cs
> +                var immichAlbums = await immichApi.GetAllAlbumsAsync(null, null);
Updated, can you approve (if you approve).

2024-06-03 06:15 UTC, JW-CH approved these changes

2024-06-03 06:15 UTC, merged